name: Deploying Infastructure to ECS
on:
     workflow_dispatch:
    
permissions:
    id-token: write
    contents: read

    
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Deployment
        steps:
             - name: Checkout
               uses: actions/checkout@v4
        
             - name: OpenID Connect
               uses: aws-actions/configure-aws-credentials@v4
               with:
                    aws-region: eu-west-2
                    role-to-assume: ${{ secrets.IAM_OIDC }}
                    audience: sts.amazonaws.com
        
            
             - name: Checkout Terraform
               uses: hashicorp/setup-terraform@v4

             - name: Initalize backend terraform
               working-directory: ./infra
               run:  terraform init

             - name: Format terraform
               working-directory: ./infra
               run: terraform fmt -recursive -diff

             - name: terraform validation
               working-directory: ./infra
               run: terraform validate
            
             - name: terraform plan
               working-directory: ./infra
               run: terraform plan

             - name: terraform apply
               working-directory: ./infra
               run: terraform apply -auto-approve

             - name: trigger ecs task deployment as requested on the assignment
               run: |
                 aws --version
                 aws ecs update-service \
                   --cluster Cluster \
                   --service ecs-service \
                   --force-new-deployment \
                   --region eu-west-2





                
            