name: Tearing up the Infrastructure
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dismantle-terraform
    env:
      CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_KEY}}
    steps:
      - name: Virtual Runner
        uses: actions/checkout@v4

      - name: OpenID Connect
        uses: aws-actions/configure-aws-credentials@v6.2.1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.IAM_OIDC }}
          audience: sts.amazonaws.com

      - name: terraform checkout
        uses: hashicorp/setup-terraform@v4

      - name: terraform init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Destroy Infastructure
        working-directory: ./infra
        run: terraform destroy -auto-approve
