name: Legacy Terraform
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Legacy-Application
    steps:
      - name: actions checkout
        uses: actions/checkout@v4

      - name: OpenID Connect
        uses: aws-actions/configure-aws-credentials@v6.2.1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.IAM_OIDC }}
          audience: sts.amazonaws.com

      - name: Terraform Actions
        uses: hashicorp/setup-terraform@v4

      - name: Check if S3 Bucket Exists, If so, Perform Initalize, Plan and Apply to Bootstrap #Done to avoid s3 bucket already exist in when automating
        working-directory: ./bootstrap
        run: |
          if aws s3api head-bucket --bucket "ec2toecsmigration" 2>dev/null; then
          echo "S3 bucket exist -> Skip"
          else
              terraform init
              terraform plan
              terraform apply -auto-approve
          fi
          
      - name: Initialize Terraform /init
        working-directory: ./ec2-legacy-app/terraform
        run: terraform init

      - name: Terraform fmt
        working-directory: ./ec2-legacy-app/terraform
        run: terraform fmt

      - name: Terraform validate
        working-directory: ./ec2-legacy-app/terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: ./ec2-legacy-app/terraform
        run: terraform apply -auto-approve

      - name: terraform Output
        working-directory: ./ec2-legacy-app/terraform
        run: terraform output
